#!/bin/bash

source "$TUIOS_PATH/config/tuios/theme/colors.sh"

export GUM_CONFIRM_PROMPT_FOREGROUND="$COLOR3"
export GUM_CONFIRM_SELECTED_FOREGROUND="0"
export GUM_CONFIRM_SELECTED_BACKGROUND="$COLOR3"
export GUM_CHOOSE_HEADER_FOREGROUND="$COLOR3"
export GUM_CHOOSE_CURSOR_FOREGROUND="$COLOR1"
export GUM_CHOOSE_CURSOR_BACKGROUND="$COLOR3"
export GUM_STYLE_BACKGROUND="6"
export GUM_STYLE_FOREGROUND="$COLOR3"
export PADDING="0 0 0 $PADDING_LEFT"
export GUM_CHOOSE_PADDING="$PADDING"
export GUM_FILTER_PADDING="$PADDING"
export GUM_INPUT_PADDING="$PADDING"
export GUM_SPIN_PADDING="$PADDING"
export GUM_TABLE_PADDING="$PADDING"
export GUM_CONFIRM_PADDING="$PADDING"
