source "$HOME/.config/zsh/base.zsh"

source "$HOME/.config/zsh/functions.zsh"
source "$HOME/.config/zsh/aliases.zsh"
source "$HOME/.config/zsh/exports.zsh"
source "$HOME/.config/zsh/sources.zsh"
for file in $HOME/.config/zsh/custom/*.zsh; do
  source "$file"
done

